Task/COOKS-310: complete saga and update selectors
TACC/protx-dashboard pull request #49
Opened 2022-10-19 17:26 UTC by ryamase

## Overview: ##
Complete new saga, update selectors, minor adjustments to chart section (e.g. instructions & new header)

## Related Jira tickets: ##

* [COOKS-123](https://jira.tacc.utexas.edu/browse/COOKS-123)

## Summary of Changes: ##

- New redux saga and reducer for getting statewide analytics charts
- Updated selectors per Juliana's design document
- Added header and updated instruction in the chart section

## Testing Steps: ##
1. Go to https://cep.test/protx/dash/analytics
2. Test the new dropdown menu for Projections and ensure that selecting each option ('Relative Risk' or 'Predicted Number of Cases') causes the intended chart to display.
3. Note any desired changes to chart header and/or instructions.

## UI Photos:
**Relative Risk Chart Selected**
![Screen Shot 2022-10-19 at 12 22 29 PM](https://user-images.githubusercontent.com/79928051/196761484-74a9ea70-af1d-4dd8-a3c3-d6bb465f04bf.png)

**Predicted Number of Cases Chart Selected**
![Screen Shot 2022-10-19 at 12 23 32 PM](https://user-images.githubusercontent.com/79928051/196761991-71b8b633-0e09-4053-a151-99d4103cafd9.png)

## Notes: ##

2022-10-19 20:53 UTC, nathanfranklin commented on protx-client/src/components/ProTx/components/charts/AnalyticsStateDistribution.jsx
> +function AnalyticsStateDistribution({geography, analyticsType}) {
suggestion: add `analyticsType` to the propTypes.

[ we don't have any client-side linting for these things at the moment. we should tackle that next sprint]

2022-10-19 20:54 UTC, nathanfranklin commented on protx-client/src/components/ProTx/components/dashboard/DisplaySelectors.jsx
> +  analyticsType,
add analyticsType and setAnalyticsType to proptypes. (probably as optional with default values of `null`)?

2022-10-19 20:56 UTC, nathanfranklin commented on protx-client/src/components/ProTx/components/dashboard/DisplaySelectors.jsx
> +  const analyticsCategories = [{name: 'risk', display_text: 'Relative Risk'}, {name: 'pred_per_100k', display_text: 'Predicted Number of Cases'}]
reminder for us to ask Juliana about the "Predicted Number of Cases " string.  I wonder if we need the a "(per 100k)" added 🤷

2022-10-19 21:08 UTC, nathanfranklin requested changes
Left some minor suggestions (mostly as our listing is not active for client-side code, I just noticed two things about properties that we can alter before merging).  Otherwise, looks good to me 👍

2022-10-19 22:10 UTC, ryamase commented
Good catch with the propTypes and defaultProps; I've made the suggested changes.

2022-10-20 03:03 UTC, nathanfranklin approved these changes
LGTM 👍

2022-10-20 03:07 UTC, merged